#CREAR BASE DE DATOS
CREATE DATABASE IF NOT EXISTS prueba;

#UTILIZAR BASE DE DATOS
USE prueba;

#CREAR TABLAS
CREATE TABLE IF NOT EXISTS customer(
	idCustomer INT AUTO_INCREMENT PRIMARY KEY,
    nameCustomer VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS supplier(
	idSupplier INT AUTO_INCREMENT PRIMARY KEY,
    nameSupplier VARCHAR(50) NOT NULL
);